name: do build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14

      - name: Check out code
        uses: actions/checkout@master

      - name: Build
        run: make all

      - name: List
        run: ls
