name: Release
on:
  create:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release on GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1
        with:
          go-version: 1.14
        id: go

      - name: Validates GO releaser config
        uses: actions/checkout@v1

      - name: Create release on GitHub
        uses: goreleaser/goreleaser-action@master
        with:
          args: release 
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}